version: '3'

services: 

  nginx:
    build:
      context: nginx
    image: samartinucci/fullcycle-nginx:latest
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: node
    image: samartinucci/fullcycle-node:latest
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge   
